<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="CategoryAdministration.aspx.cs" Inherits="KMWeb.Administration.CategoryAdministration" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<asp:TextBox runat="server" id="HiddenField1" ></asp:TextBox>

    <div>
      <asp:GridView ID="gvKategorije" runat="server" AutoGenerateSelectButton="True" 
                    DataKeyNames = "IdKategorija" AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" onrowdeleting="gvKategorije_RowDeleting" 
            onselectedindexchanged="gvKategorije_SelectedIndexChanged">
                   <Columns>
                        <asp:BoundField DataField="IdKategorija" HeaderText="Id" Visible="true"/>
                        <asp:BoundField DataField="NazivKategorije" HeaderText="Naziv" />   
                        <asp:BoundField DataField="OpisKategorije" HeaderText="Opis" /> 
                        <asp:BoundField DataField="DatumKreiranja" HeaderText="DatumKreiranja" /> 
                         <asp:BoundField DataField="KorisnickoIme" HeaderText="Kreirao" /> 
                        <asp:BoundField DataField="CancelDate" HeaderText="CancelDate" /> 
                        <asp:BoundField DataField="CancelUser" HeaderText="CancelUser" />
                      </Columns>
      </asp:GridView>
    </div>


</asp:Content>